# Generated by Django 3.1.2 on 2020-11-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0003_auto_20201103_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
