# Generated by Django 3.1.2 on 2020-10-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0003_auto_20201026_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
