# Generated by Django 3.1.2 on 2020-10-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0004_auto_20201026_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
