# Generated by Django 3.1.2 on 2020-10-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0005_auto_20201026_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
