# Generated by Django 3.1.2 on 2020-10-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0006_auto_20201026_1400'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
