# Generated by Django 3.1.2 on 2020-11-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0006_auto_20201104_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='login_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
