# Generated by Django 3.1.2 on 2020-11-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0007_auto_20201104_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default='', max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
