# Generated by Django 3.1.2 on 2020-10-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0010_auto_20201026_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default='93db1cca', max_length=8, primary_key=True, serialize=False),
        ),
    ]
