# Generated by Django 3.1.2 on 2020-10-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0011_auto_20201027_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
