# Generated by Django 3.1.2 on 2020-10-28 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0012_auto_20201028_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='update_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
