# Generated by Django 3.1.2 on 2020-10-28 09:38

import azatAI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0013_users_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='delete_date',
            field=models.DateField(default=azatAI.models.get_deadline),
        ),
    ]
