# Generated by Django 3.1.2 on 2020-10-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0014_users_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
