# Generated by Django 3.1.2 on 2020-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0015_auto_20201028_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
