# Generated by Django 3.1.2 on 2020-11-02 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0016_users_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='delete_date',
            new_name='session_expire',
        ),
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='users',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=8, unique=True)),
                ('device_os', models.CharField(max_length=50)),
                ('login_date', models.DateField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='azatAI.users')),
            ],
        ),
    ]
