# Generated by Django 3.1.2 on 2020-11-02 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0018_auto_20201102_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='azatAI.users'),
        ),
    ]
