# Generated by Django 3.1.2 on 2020-11-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azatAI', '0019_auto_20201102_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='device_os',
            field=models.CharField(max_length=8),
        ),
    ]
